<a href="https://colab.research.google.com/github/sluggishpoem/Mineria-de-datos/blob/main/Mineria_de_datos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Mineria de Datos

##Primer Parcial

###Introduccion

####Ciencia de Datos

####Conceptos

Mineria de Datos:

La minería de datos es un proceso que utiliza el machine learning y el análisis estadístico para descubrir patrones y correlaciones en grandes conjuntos de datos. Este proceso permite explorar grandes volúmenes de información para encontrar patrones ocultos, tendencias y reglas que no son fácilmente visibles a simple vista. Es una disciplina clave dentro del big data que ayuda a predecir resultados y tomar decisiones informadas.

####Ciencia de Datos

In [ ]:
#La funcion help nos muestra la ayuda
help(len)

Help on built-in function len in module builtins:

len(obj, /)
    Return the number of items in a container.



In [ ]:
#Crear lista
L=[1,2,3]
L.insert?

In [ ]:
#Ejemplo con una función con Docstring
def square(a):
  """Return the square of a."""
  return a ** 2

In [ ]:
square?

In [ ]:
square??

In [ ]:
from itemtools

La ciencia de datos es un campo interdisciplinario que combina matemáticas, estadística, programación, inteligencia artificial (IA) y aprendizaje automático (machine learning) para analizar grandes volúmenes de datos estructurados y no estructurados. Su objetivo principal es extraer información valiosa que permita tomar decisiones estratégicas y resolver problemas empresariales.

Este campo abarca todo el ciclo de vida de los datos, desde su recopilación hasta la comunicación de resultados. Incluye procesos como la limpieza, transformación, análisis exploratorio, modelado predictivo y visualización de datos. Los científicos de datos utilizan herramientas como Python, R, y plataformas como Apache Spark o TensorFlow para realizar estas tareas.

####IPython Magic Commands

In [ ]:
#Sirve para evaluar el desempeño  de una expresion en cuanto a tiempo
%timeit  L = [n ** 2 for n in range(1000)]

114 µs ± 53.8 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [ ]:
#Con doble porcentaje podemos evaluar el desempeño
#en cuanto a tiempo de más de una línea de tiempo
%%timeit
L = []
for n in range(1000):
  L.append(n ** 2)

80 µs ± 1.37 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


IPython and shell commands

In [ ]:
!ls

sample_data


In [ ]:
!pwd

/content


In [ ]:
contents = !ls

In [ ]:
print(contents)

['sample_data']


In [ ]:
directory = !pwd

In [ ]:
print(directory)

['/content']


In [ ]:
message = "Hello from python"

In [ ]:
%cd /content/


/content


In [ ]:
%cd sample_data

[Errno 2] No such file or directory: 'sample_data'
/content/sample_data


####Understanding data types on Python

Creating Arrays from Python Lists

In [ ]:
#Importa numpy y renombra como np
import numpy as np

In [ ]:
#Arreglo numoy de arreglos
np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

In [ ]:
#Arreglo de flotantes
np.array([3.14, 4, 2, 3])


array([3.14, 4.  , 2.  , 3.  ])

In [ ]:
#Se puede especificar que tipo de datos buscamos
np.array([1, 2, 3, 4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

In [ ]:
#Cuando el argumento de np.array de una iteracion pueden ser , multidimensionales
#utilizando lista de listas
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

Creating Arrays form Scratch

In [ ]:
import numpy as np

In [ ]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
#Es dicktypes no dicktype
np.ones((3,5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
#Random array de 3x3
np.random.random((3,3))

array([[0.02308536, 0.2151658 , 0.60543688],
       [0.84038029, 0.13720392, 0.1073699 ],
       [0.9468029 , 0.55742423, 0.6923635 ]])

In [ ]:
#Cuando es normal se refiere a la campana de gauss,
#que sera probable que caiga en los centros
#Palabra clave: Agujas-dicktype
np.random.normal(21,1,5)

array([21.93066889, 21.45156485, 20.58870956, 20.3829287 , 21.13250421])

In [ ]:
#Arreglo random de 3x3 del 0 al 9
np.random.randint(0,10,(3,3))

array([[3, 8, 6],
       [0, 5, 1],
       [4, 7, 7]])

In [ ]:
#Matriz identidad
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
#
np.empty(3)

array([1., 1., 1.])

In [ ]:
np.random.seed(0)

x1= np.random.randint(10, size=6)
x2= np.random.randint(10, size=(3,4))
x3= np.random.randint(10, size=(3,4,5))

Array Indexing: Accessing Single Elements

In [ ]:
x1

array([5, 0, 3, 3, 7, 9])

In [ ]:
x1[0]


np.int64(5)

In [ ]:
x1[3]

np.int64(3)

In [ ]:
x1[-2]

np.int64(7)

In [ ]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [ ]:
x2[-1,-1]=2
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 2]])

####Analisis Estadistico Basico con NumPy

Media

In [ ]:
data = np.array([1, 2, 3, 4, 5])
media = np.mean(data)
print(media)

3.0


In [ ]:
data = np.array([1, 2, 3, 4, 5])
weights = np.array([1, 2, 3, 4, 5])
promedio = np.average(data)
promedio_ponderado = np.average(data, weights=weights)

print(promedio)
print(promedio_ponderado)


3.0
3.6666666666666665


Mediana

In [ ]:
mediana = np.median(data)

Varianza y Desviación Estándar

In [ ]:
varianza = np.var(data)
desviacion = np.std(data)
print(varianza)
print(desviacion)

2.0
1.4142135623730951


Generación de Datos Aleatorios

In [ ]:
muestra = np.random.normal(0, 1, 1000)
print(np.mean(muestra), np.std(muestra))

-0.006543456960417206 1.0059985778093545


Correlación

In [ ]:
corr = np.corrcoef([1,2,3], [1,5,7])
print(corr)

[[1.         0.98198051]
 [0.98198051 1.        ]]


Funciones Estadísticas Adicionales (NumPy)

In [ ]:
#Cuantiles (np.quantile)
#Percentiles (np.percentile)
#Histogramas (np.histogram)
#Covarianza (np.cov)
#Manejo de NaN (np.nanmean, etc.)

Conclusión

NumPy facilita el análisis estadístico al proporcionar funciones optimizadas para cálculos comunes como media, mediana, varianza, desviación estándar y correlación. Además, ofrece herramientas para generar datos y analizar distribuciones.

####Cuadros Estadistico

In [1]:
import numpy as np
import pandas as pd
from io import StringIO

raw = """Marca temporal\tNúmero de matrícula\t¿Cuántos años cumplidos tienes?\t¿Has realizado programas utilizando Python?\t¿Has utilizado Google Colab?\t¿Tienes cuenta de GitHub?
19/01/2026 18:32:18\t178920\t22\tSi\tNo\tSi
19/01/2026 18:32:23\t182712\t21\tSi\tNo\tSi
19/01/2026 18:32:25\t180370\t26\tSi\tSi\tSi
19/01/2026 18:32:27\t182570\t21\tSi\tSi\tSi
19/01/2026 18:32:28\t177622\t24\tSi\tNo\tSi
19/01/2026 18:32:29\t175166\t22\tSi\tSi\tSi
19/01/2026 18:32:30\t177573\t22\tSi\tSi\tSi
19/01/2026 18:32:35\t178430\t21\tSi\tSi\tSi
19/01/2026 18:32:38\t179169\t23\tSi\tNo\tSi
19/01/2026 18:32:41\t177263\t22\tSi\tSi\tSi
19/01/2026 18:32:48\t179884\t23\tSi\tNo\tSi
19/01/2026 18:32:48\t183016\t22\tSi\tNo\tSi
19/01/2026 18:32:50\t179033\t23\tSi\tSi\tNo
19/01/2026 18:32:54\t178218\t22\tSi\tNo\tSi
19/01/2026 18:32:55\t178446\t22\tSi\tSi\tSi
19/01/2026 18:33:00\t178166\t22\tSi\tSi\tNo
19/01/2026 18:33:02\t177406\t22\tSi\tNo\tSi
19/01/2026 18:33:05\t177192\t22\tSi\tSi\tSi
19/01/2026 18:33:08\t182451\t21\tSi\tNo\tSi
19/01/2026 18:33:08\t171513\t24\tNo\tNo\tSi
19/01/2026 18:33:09\t181619\t21\tSi\tNo\tSi
19/01/2026 18:33:12\t182298\t23\tSi\tNo\tSi
19/01/2026 18:33:14\t181419\t24\tNo\tNo\tSi
19/01/2026 18:33:32\t177291\t21\tSi\tSi\tSi
19/01/2026 18:33:42\t182085\t22\tSi\tNo\tSi
19/01/2026 18:33:53\t176453\t22\tSi\tNo\tSi
19/01/2026 18:34:04\t176263\t24\tSi\tNo\tSi
19/01/2026 18:34:06\t179997\t21\tSi\tNo\tSi
19/01/2026 18:36:21\t175842\t23\tSi\tNo\tNo
19/01/2026 20:19:21\t179913\t20\tSi\tNo\tSi
19/01/2026 20:19:48\t177301\t22\tSi\tSi\tNo
19/01/2026 20:20:06\t183060\t21\tSi\tNo\tSi
19/01/2026 20:20:08\t177935\t22\tSi\tSi\tSi
19/01/2026 20:20:19\t177700\t20\tSi\tSi\tSi
19/01/2026 20:20:26\t178318\t24\tSi\tSi\tSi
19/01/2026 20:20:27\t174653\t24\tSi\tNo\tSi
19/01/2026 20:20:29\t177139\t21\tSi\tNo\tSi
19/01/2026 20:20:31\t173479\t25\tSi\tNo\tNo
19/01/2026 20:20:39\t175588\t23\tNo\tNo\tSi
19/01/2026 20:20:45\t178774\t23\tSi\tSi\tSi
19/01/2026 20:20:45\t175031\t23\tSi\tNo\tNo
19/01/2026 20:20:49\t178396\t21\tSi\tSi\tSi
19/01/2026 20:20:49\t172068\t23\tNo\tNo\tNo
19/01/2026 20:20:50\t174197\t23\tNo\tNo\tSi
19/01/2026 20:20:55\t178584\t22\tSi\tNo\tSi
19/01/2026 20:20:55\t175329\t24\tSi\tNo\tSi
19/01/2026 20:20:56\t177685\t22\tSi\tSi\tSi
19/01/2026 20:20:57\t178678\t22\tNo\tNo\tSi
19/01/2026 20:21:04\t177143\t22\tSi\tNo\tSi
19/01/2026 20:21:07\t182318\t26\tSi\tNo\tSi
19/01/2026 20:21:27\t182377\t20\tSi\tNo\tSi
19/01/2026 20:21:34\t179419\t22\tSi\tNo\tNo
19/01/2026 20:21:35\t181662\t21\tSi\tNo\tSi
19/01/2026 20:21:38\t181760\t21\tSi\tNo\tSi
19/01/2026 20:22:06\t177888\t22\tSi\tNo\tSi
19/01/2026 20:22:15\t176535\t25\tSi\tNo\tSi
19/01/2026 20:22:29\t179862\t21\tSi\tNo\tSi
19/01/2026 20:22:32\t178378\t22\tSi\tNo\tSi
19/01/2026 20:22:50\t177451\t22\tSi\tNo\tSi
19/01/2026 20:23:15\t179804\t21\tSi\tNo\tSi
"""

# Cargar datos
df = pd.read_csv(StringIO(raw), sep='\t')
df.columns = [c.strip() for c in df.columns]

# Variables
df['edad'] = pd.to_numeric(df['¿Cuántos años cumplidos tienes?'], errors='coerce')
map_sn = {'Si': True, 'No': False}
df['prog_python'] = df['¿Has realizado programas utilizando Python?'].map(map_sn)
df['usa_colab'] = df['¿Has utilizado Google Colab?'].map(map_sn)
df['cuenta_github'] = df['¿Tienes cuenta de GitHub?'].map(map_sn)

In [2]:
df.head()

Marca temporal  Número de matrícula  ¿Cuántos años cumplidos tienes?  \
0  19/01/2026 18:32:18               178920                               22   
1  19/01/2026 18:32:23               182712                               21   
2  19/01/2026 18:32:25               180370                               26   
3  19/01/2026 18:32:27               182570                               21   
4  19/01/2026 18:32:28               177622                               24   

  ¿Has realizado programas utilizando Python? ¿Has utilizado Google Colab?  \
0                                          Si                           No   
1                                          Si                           No   
2                                          Si                           Si   
3                                          Si                           Si   
4                                          Si                           No   

  ¿Tienes cuenta de GitHub?  edad  prog_python  usa_colab  cuenta_github  
0                        Si    22         True      False           True  
1                        Si    21         True      False           True  
2                        Si    26         True       True           True  
3                        Si    21         True       True           True  
4                        Si    24         True      False           True

In [3]:
# A NumPy
edad = df['edad'].to_numpy(dtype=float)
prog_py = df['prog_python'].to_numpy(dtype=bool)
usa_colab = df['usa_colab'].to_numpy(dtype=bool)
cuenta_gh = df['cuenta_github'].to_numpy(dtype=bool)

In [7]:
print(f'ndarray edad primeros Cinco elementos: {edad[:5]}')
print(f'ndarray prog_py primeros Cinco elementos: {prog_py[:5]}')
print(f'ndarray usa_colab primeros Cinco elementos: {usa_colab[:5]}')
print(f'ndarray cuenta_gh ultimos Cinco elementos: {cuenta_gh[-5:]}')

ndarray edad primeros Cinco elementos: [22. 21. 26. 21. 24.]
ndarray prog_py primeros Cinco elementos: [ True  True  True  True  True]
ndarray usa_colab primeros Cinco elementos: [False False  True  True False]
ndarray cuenta_ghprimeros Cinco elementos: [ True  True  True  True  True]


In [8]:
# Descriptivos de edad (NumPy)
summary_age = {
    'n': int(edad.size),
    'min': float(np.min(edad)),
    'p25': float(np.percentile(edad, 25)),
    'mediana': float(np.median(edad)),
    'media': float(np.mean(edad)),
    'p75': float(np.percentile(edad, 75)),
    'max': float(np.max(edad)),
    'rango(ptp)': float(np.ptp(edad)),
    'var_muestral': float(np.var(edad, ddof=1)),
    'std_muestral': float(np.std(edad, ddof=1)),
    'cv': float(np.std(edad, ddof=1)/np.mean(edad)),
}

In [9]:
summary_age

{'n': 60,
 'min': 20.0,
 'p25': 21.0,
 'mediana': 22.0,
 'media': 22.3,
 'p75': 23.0,
 'max': 26.0,
 'rango(ptp)': 6.0,
 'var_muestral': 1.8406779661016948,
 'std_muestral': 1.3567158752302173,
 'cv': 0.06083927691615324}

In [10]:
# Frecuencias (NumPy)
freq_python = {'Si': int(np.count_nonzero(prog_py)), 'No': int(edad.size - np.count_nonzero(prog_py))}
freq_colab  = {'Si': int(np.count_nonzero(usa_colab)), 'No': int(edad.size - np.count_nonzero(usa_colab))}
freq_gh     = {'Si': int(np.count_nonzero(cuenta_gh)), 'No': int(edad.size - np.count_nonzero(cuenta_gh))}

In [11]:
print(f'frecuencia de utilizar Python: {freq_python}')
print(f'frecuencia de utilizar Colab: {freq_colab}')
print(f'frecuencia de utilizar GitHub: {freq_gh}')

frecuencia de utilizar Python: {'Si': 54, 'No': 6}
frecuencia de utilizar Colab: {'Si': 18, 'No': 42}
frecuencia de utilizar GitHub: {'Si': 52, 'No': 8}


In [12]:
# Tablas cruzadas (NumPy)
def tabla2x2(a, b):
    t = np.zeros((2,2), dtype=int)
    t[1,1] = np.count_nonzero(a & b)
    t[1,0] = np.count_nonzero(a & ~b)
    t[0,1] = np.count_nonzero(~a & b)
    t[0,0] = np.count_nonzero(~a & ~b)
    return t

tab_py_colab = tabla2x2(prog_py, usa_colab)
tab_py_gh    = tabla2x2(prog_py, cuenta_gh)
tab_colab_gh = tabla2x2(usa_colab, cuenta_gh)

In [14]:
print(f'Tabla Python vs Colab \n {tab_py_colab}')
print(f'Tabla Python vs Github \n {tab_py_gh}')
print(f'Tabla Colab vs Github \n {tab_colab_gh}')


Tabla Python vs Colab 
 [[ 6  0]
 [36 18]]
Tabla Python vs Github 
 [[ 1  5]
 [ 7 47]]
Tabla Colab vs Github 
 [[ 5 37]
 [ 3 15]]


In [15]:
# Medias de edad por grupo (NumPy)
means_by_group = {
    'edad_promedio_Python': {'Si': float(np.mean(edad[prog_py])) if np.any(prog_py) else np.nan,
                             'No': float(np.mean(edad[~prog_py])) if np.any(~prog_py) else np.nan},
    'edad_promedio_Colab':  {'Si': float(np.mean(edad[usa_colab])) if np.any(usa_colab) else np.nan,
                             'No': float(np.mean(edad[~usa_colab])) if np.any(~usa_colab) else np.nan},
    'edad_promedio_GitHub': {'Si': float(np.mean(edad[cuenta_gh])) if np.any(cuenta_gh) else np.nan,
                             'No': float(np.mean(edad[~cuenta_gh])) if np.any(~cuenta_gh) else np.nan},
}

summary_age, freq_python, freq_colab, freq_gh, tab_py_colab, tab_py_gh, tab_colab_gh, means_by_group

({'n': 60,
  'min': 20.0,
  'p25': 21.0,
  'mediana': 22.0,
  'media': 22.3,
  'p75': 23.0,
  'max': 26.0,
  'rango(ptp)': 6.0,
  'var_muestral': 1.8406779661016948,
  'std_muestral': 1.3567158752302173,
  'cv': 0.06083927691615324},
 {'Si': 54, 'No': 6},
 {'Si': 18, 'No': 42},
 {'Si': 52, 'No': 8},
 array([[ 6,  0],
        [36, 18]]),
 array([[ 1,  5],
        [ 7, 47]]),
 array([[ 5, 37],
        [ 3, 15]]),
 {'edad_promedio_Python': {'Si': 22.203703703703702, 'No': 23.166666666666668},
  'edad_promedio_Colab': {'Si': 22.11111111111111, 'No': 22.38095238095238},
  'edad_promedio_GitHub': {'Si': 22.21153846153846, 'No': 22.875}})

In [16]:
raw = """Marca temporal,Número de matrícula,¿Cuántos años cumplidos tienes?,¿Has realizado programas utilizando Python?,¿Has utilizado Google Colab?,¿Tienes cuenta de GitHub?
19/01/2026 18:32:18,178920,22,Si,No,Si
19/01/2026 18:32:23,182712,21,Si,No,Si
19/01/2026 18:32:25,180370,26,Si,Si,Si
19/01/2026 18:32:27,182570,21,Si,Si,Si
19/01/2026 18:32:28,177622,24,Si,No,Si
19/01/2026 18:32:29,175166,22,Si,Si,Si
19/01/2026 18:32:30,177573,22,Si,Si,Si
19/01/2026 18:32:35,178430,21,Si,Si,Si
19/01/2026 18:32:38,179169,23,Si,No,Si
19/01/2026 18:32:41,177263,22,Si,Si,Si
19/01/2026 18:32:48,179884,23,Si,No,Si
19/01/2026 18:32:48,183016,22,Si,No,Si
19/01/2026 18:32:50,179033,23,Si,Si,No
19/01/2026 18:32:54,178218,22,Si,No,Si
19/01/2026 18:32:55,178446,22,Si,Si,Si
19/01/2026 18:33:00,178166,22,Si,Si,No
19/01/2026 18:33:02,177406,22,Si,No,Si
19/01/2026 18:33:05,177192,22,Si,Si,Si
19/01/2026 18:33:08,182451,21,Si,No,Si
19/01/2026 18:33:08,171513,24,No,No,Si
19/01/2026 18:33:09,181619,21,Si,No,Si
19/01/2026 18:33:12,182298,23,Si,No,Si
19/01/2026 18:33:14,181419,24,No,No,Si
19/01/2026 18:33:32,177291,21,Si,Si,Si
19/01/2026 18:33:42,182085,22,Si,No,Si
19/01/2026 18:33:53,176453,22,Si,No,Si
19/01/2026 18:34:04,176263,24,Si,No,Si
19/01/2026 18:34:06,179997,21,Si,No,Si
19/01/2026 18:36:21,175842,23,Si,No,No
19/01/2026 20:19:21,179913,20,Si,No,Si
19/01/2026 20:19:48,177301,22,Si,Si,No
19/01/2026 20:20:06,183060,21,Si,No,Si
19/01/2026 20:20:08,177935,22,Si,Si,Si
19/01/2026 20:20:19,177700,20,Si,Si,Si
19/01/2026 20:20:26,178318,24,Si,Si,Si
19/01/2026 20:20:27,174653,24,Si,No,Si
19/01/2026 20:20:29,177139,21,Si,No,Si
19/01/2026 20:20:31,173479,25,Si,No,No
19/01/2026 20:20:39,175588,23,No,No,Si
19/01/2026 20:20:45,178774,23,Si,Si,Si
19/01/2026 20:20:45,175031,23,Si,No,No
19/01/2026 20:20:49,178396,21,Si,Si,Si
19/01/2026 20:20:49,172068,23,No,No,No
19/01/2026 20:20:50,174197,23,No,No,Si
19/01/2026 20:20:55,178584,22,Si,No,Si
19/01/2026 20:20:55,175329,24,Si,No,Si
19/01/2026 20:20:56,177685,22,Si,Si,Si
19/01/2026 20:20:57,178678,22,No,No,Si
19/01/2026 20:21:04,177143,22,Si,No,Si
19/01/2026 20:21:07,182318,26,Si,No,Si
19/01/2026 20:21:27,182377,20,Si,No,Si
19/01/2026 20:21:34,179419,22,Si,No,No
19/01/2026 20:21:35,181662,21,Si,No,Si
19/01/2026 20:21:38,181760,21,Si,No,Si
19/01/2026 20:22:06,177888,22,Si,No,Si
19/01/2026 20:22:15,176535,25,Si,No,Si
19/01/2026 20:22:29,179862,21,Si,No,Si
19/01/2026 20:22:32,178378,22,Si,No,Si
19/01/2026 20:22:50,177451,22,Si,No,Si
19/01/2026 20:23:15,179804,21,Si,No,Si
"""

# Cargar datos
df = pd.read_csv(StringIO(raw.csv), sep='\t')
df.columns = [c.strip() for c in df.columns]
# Variables
df['edad'] = pd.to_numeric(df['¿Cuántos años cumplidos tienes?'], errors='coerce')
map_sn = {'Si': True, 'No': False}
df['prog_python'] = df['¿Has realizado programas utilizando Python?'].map(map_sn)
df['usa_colab'] = df['¿Has utilizado Google Colab?'].map(map_sn)
df['cuenta_github'] = df['¿Tienes cuenta de GitHub?'].map(map_sn)

AttributeError: 'str' object has no attribute 'csv'