<a href="https://colab.research.google.com/github/sluggishpoem/Mineria-de-datos/blob/main/Mineria_de_datos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Mineria de Datos

##Primer Parcial

###Introduccion

####Ciencia de Datos

####Conceptos

Mineria de Datos:

La minería de datos es un proceso que utiliza el machine learning y el análisis estadístico para descubrir patrones y correlaciones en grandes conjuntos de datos. Este proceso permite explorar grandes volúmenes de información para encontrar patrones ocultos, tendencias y reglas que no son fácilmente visibles a simple vista. Es una disciplina clave dentro del big data que ayuda a predecir resultados y tomar decisiones informadas.

####Ciencia de Datos

In [ ]:
#La funcion help nos muestra la ayuda
help(len)

Help on built-in function len in module builtins:

len(obj, /)
    Return the number of items in a container.



In [ ]:
#Crear lista
L=[1,2,3]
L.insert?

In [ ]:
#Ejemplo con una función con Docstring
def square(a):
  """Return the square of a."""
  return a ** 2

In [ ]:
square?

In [ ]:
square??

In [ ]:
from itemtools

La ciencia de datos es un campo interdisciplinario que combina matemáticas, estadística, programación, inteligencia artificial (IA) y aprendizaje automático (machine learning) para analizar grandes volúmenes de datos estructurados y no estructurados. Su objetivo principal es extraer información valiosa que permita tomar decisiones estratégicas y resolver problemas empresariales.

Este campo abarca todo el ciclo de vida de los datos, desde su recopilación hasta la comunicación de resultados. Incluye procesos como la limpieza, transformación, análisis exploratorio, modelado predictivo y visualización de datos. Los científicos de datos utilizan herramientas como Python, R, y plataformas como Apache Spark o TensorFlow para realizar estas tareas.

####IPython Magic Commands

In [ ]:
#Sirve para evaluar el desempeño  de una expresion en cuanto a tiempo
%timeit  L = [n ** 2 for n in range(1000)]

114 µs ± 53.8 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [ ]:
#Con doble porcentaje podemos evaluar el desempeño
#en cuanto a tiempo de más de una línea de tiempo
%%timeit
L = []
for n in range(1000):
  L.append(n ** 2)

80 µs ± 1.37 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


IPython and shell commands

In [ ]:
!ls

sample_data


In [ ]:
!pwd

/content


In [ ]:
contents = !ls

In [ ]:
print(contents)

['sample_data']


In [ ]:
directory = !pwd

In [ ]:
print(directory)

['/content']


In [ ]:
message = "Hello from python"

In [ ]:
%cd /content/


/content


In [ ]:
%cd sample_data

[Errno 2] No such file or directory: 'sample_data'
/content/sample_data


####Understanding data types on Python

Creating Arrays from Python Lists

In [ ]:
#Importa numpy y renombra como np
import numpy as np

In [ ]:
#Arreglo numoy de arreglos
np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

In [ ]:
#Arreglo de flotantes
np.array([3.14, 4, 2, 3])


array([3.14, 4.  , 2.  , 3.  ])

In [ ]:
#Se puede especificar que tipo de datos buscamos
np.array([1, 2, 3, 4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

In [ ]:
#Cuando el argumento de np.array de una iteracion pueden ser , multidimensionales
#utilizando lista de listas
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

Creating Arrays form Scratch

In [1]:
import numpy as np

In [2]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [4]:
#Es dicktypes no dicktype
np.ones((3,5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [6]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [7]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [8]:
#Random array de 3x3
np.random.random((3,3))

array([[0.02308536, 0.2151658 , 0.60543688],
       [0.84038029, 0.13720392, 0.1073699 ],
       [0.9468029 , 0.55742423, 0.6923635 ]])

In [12]:
#Cuando es normal se refiere a la campana de gauss,
#que sera probable que caiga en los centros
#Palabra clave: Agujas-dicktype
np.random.normal(21,1,5)

array([21.93066889, 21.45156485, 20.58870956, 20.3829287 , 21.13250421])

In [14]:
#Arreglo random de 3x3 del 0 al 9
np.random.randint(0,10,(3,3))

array([[3, 8, 6],
       [0, 5, 1],
       [4, 7, 7]])

In [15]:
#Matriz identidad
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [16]:
#
np.empty(3)

array([1., 1., 1.])

In [22]:
np.random.seed(0)

x1= np.random.randint(10, size=6)
x2= np.random.randint(10, size=(3,4))
x3= np.random.randint(10, size=(3,4,5))

Array Indexing: Accessing Single Elements

In [19]:
x1

array([5, 0, 3, 3, 7, 9])

In [20]:
x1[0]


np.int64(5)

In [21]:
x1[3]

np.int64(3)

In [23]:
x1[-2]

np.int64(7)

In [24]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [26]:
x2[-1,-1]=2
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 2]])

####Analisis Estadistico Basico con NumPy